target: src.ags.grad.agc.AGC
name: agc
params:
  clip_factor: 0.01       # hệ số clipping (giống paper)
  eps: 1e-3               # tránh chia cho 0
  exclude_bias: true      # không áp dụng AGC cho bias/LayerNorm
