# configs/dataset/mnist.yaml
target: src.ags.data.fashion-mnist.FashionMNISTDataModule
params:
  name: fashion-mnist
  num_classes: 10
  img_size: 28
  in_channels: 1
  num_data: 10000
  path: data/processed/fashion-mnist
